export * from './diploma-number-input'
export * from './diploma-series-input'
export * from './education-select'
export * from './ending-input'
export * from './nostrification-checkbox'
export * from './qualification-input'
export * from './speciality-input'
export * from './university-select'
